name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build release artifacts
      run: ./gradlew build :sample:assembleRelease --stacktrace

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          sample/build/outputs/apk/release/*.apk
        body: |
          ## String Obfuscator v${{ steps.get_version.outputs.VERSION }}

          ### Features
          - Compile-time string obfuscation
          - Zero runtime overhead
          - Multi-layer security (XOR + Bit Shuffle + Base64)

          ### Installation
          See [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for installation instructions.

          ### Changes
          See commit history for details.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
