name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build release artifacts
      run: gradle build :sample:assembleRelease --stacktrace

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          sample/build/outputs/apk/release/*.apk
        body: |
          ## String Obfuscator v${{ steps.get_version.outputs.VERSION }}

          ### Features
          - Compile-time string obfuscation
          - Zero runtime overhead
          - Multi-layer security (XOR + Bit Shuffle + Base64)

          ### Installation
          ```gradle
          implementation("com.github.Ealireza.StringObfuscator:annotation:${{ steps.get_version.outputs.VERSION }}")
          implementation("com.github.Ealireza.StringObfuscator:runtime:${{ steps.get_version.outputs.VERSION }}")
          ksp("com.github.Ealireza.StringObfuscator:processor:${{ steps.get_version.outputs.VERSION }}")
          ```

          See [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for full installation instructions.

          ### Changes
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
